apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
   stripe-secret-key: "<STRIPE_SECRET_KEY>"
   stripe-webhook-key: "<STRIPE_WEBHOOK_KEY>"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
stringData:
  uri: "<MONGODB_URI>"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
type: Opaque
stringData:
  osrm: "<OSRM_API>"
